COOKIES = {
#    "001me" : "BDUSS=lI5MmtHVmh5MHdJcTFUU0R4cjl3U2VRTEJtWHBsMjNmcVRkcWROOUxSZ2gxejVjQVFBQUFBJCQAAAAAAAAAAAEAAACmKrInv8lp0MQwwO8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFKF1whShdcU",
    "1320056496@qq.com" : "BDUSS=mhsRmxnYWhjVy1BRm1peWxXQ3ZqZE5YV21LczBaNkNCUkwxekFSZi05LTJNVUZjQVFBQUFBJCQAAAAAAAAAAAEAAADjh4xSxuLL2LO-sKMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALakGVy2pBlcM"
    }
KEYWORDS = {
    "故宫" : {"finish":"0"},
    "天坛" : {"finish":"0"},
    "张家界" : {"finish":"0"},
    "长城" : {"finish":"0"},
    "颐和园" : {"finish":"0"},
    "天安门" : {"finish":"0"}
}

#random.choice(list(useful_proxies))